---
version: '2'

services:
  zcashd:
    image: electriccoinco/zcashd:latest
    volumes:
      - $ZCASHD_DATADIR:/srv/zcashd/.zcash
      - $ZCASHD_PARMDIR:/srv/zcashd/.zcash-params
    env_file:
      - .env
    ports:
      - "$ZCASHD_RPCPORT:$ZCASHD_RPCPORT"
    mem_limit: 4G
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  ecc_zcashd_exporter:
    build: .
    env_file:
      - .env
    ports:
      - "9100:9100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: grafana/grafana:8.2.2
    entrypoint:
      - bash
      - -c
      - grafana-cli plugins install grafana-piechart-panel && /run.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - promethus_data:/promethus_data
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: grafana/loki:master
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

volumes:
  promethus_data:
